import { PageHero } from '@/components/ui';
import { PersonGrid } from '@/components/people/PersonGrid';
import { getPageContent, getPeople } from '@/lib/sanity/data';

export const metadata = { title: 'Über uns' };

export default async function AboutPage() {
  const [board, content] = await Promise.all([getPeople(), getPageContent('ueber-uns')]);
  return <><PageHero eyebrow={content?.eyebrow || 'Über uns'} title={content?.title || 'Führung gemeinsam gestalten.'} text={content?.intro || 'Der Verein bildet die Basis des Netzwerks und arbeitet unabhängig von Unternehmen, Parteien und Interessenverbänden.'} image={content?.heroImage} /><section className="container grid gap-12 md:grid-cols-[.8fr_1.2fr]"><h2 className="h2">Wofür wir stehen.</h2><div className="text-lg leading-relaxed"><p>Wir machen Frauen in Führung sichtbar und fördern Gleichberechtigung im beruflichen und öffentlichen Leben. Der Verein kuratiert das Netzwerk mit fachlicher Expertise und einem klaren Fokus auf Vernetzung.</p><div className="mt-10 grid gap-6 sm:grid-cols-2"><p><b>Unternehmensübergreifend.</b><br />Erfahrungen teilen und gegenseitig unterstützen.</p><p><b>Mit Haltung.</b><br />Vorbilder sichtbar machen und weiblichen Führungsnachwuchs fördern.</p></div></div></section><section className="border-y border-[var(--line)] bg-white"><div className="container"><p className="eyebrow">Vorstand</p><h2 className="h2 mt-5 mb-14">Engagiert für das Netzwerk.</h2><PersonGrid people={board} /></div></section><section className="border-t border-[var(--line)]"><div className="container grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Geschichte</p><h2 className="h2 mt-5">Wie alles begann.</h2></div><ol className="timeline"><li><b>2016</b><p>Erste Ideen für ein regionales Führungsfrauennetzwerk.</p></li><li><b>2018</b><p>Öffentliche Veranstaltungen und erste Arbeitsgruppen entstehen.</p></li><li><b>30. Januar 2020</b><p>Vereinsgründung und Wahl des Vorstands.</p></li></ol></div></section></>;
}
