import { Button, PageHero } from '@/components/ui';
import { getPageContent } from '@/lib/sanity/data';

export const metadata = { title: 'Netzwerk' };

export default async function Network() {
  const content = await getPageContent('netzwerk');
  return <><PageHero eyebrow={content?.eyebrow || 'Netzwerk'} title={content?.title || 'Ein Netzwerk für Frauen, die führen können und wollen.'} text={content?.intro || 'Austausch, Kontakte und ein gemeinsames Ziel verbinden Frauen in Führung in der Region Heilbronn.'} image={content?.heroImage} /><section className="container grid gap-12 py-24 md:grid-cols-2"><div className="media min-h-[430px]" /><div><h2 className="h2">Vielfältig in Erfahrung und Perspektive.</h2><p className="mt-7 text-lg leading-relaxed">Im Netzwerk treffen Unternehmerinnen und Gründerinnen auf Frauen aus Management, Mittelstand, Konzernen, Forschung und Wissenschaft. Persönliche Kontakte und Events schaffen eine Plattform für Begegnung.</p><div className="mt-9"><Button href="/kontakt">Teil des Netzwerks werden</Button></div></div></section><section className="border-y border-[var(--line)] bg-white py-24"><div className="container grid gap-8 md:grid-cols-3">{[['Austausch', 'Erfahrungen teilen, Fragen stellen, Perspektiven öffnen.'], ['Verbindung', 'Brücken zwischen Menschen und Institutionen bauen.'], ['Sichtbarkeit', 'Vorbilder zeigen und Frauen in Führung stärken.']].map((item) => <div className="border-t border-[var(--ink)] pt-5" key={item[0]}><h2 className="serif text-3xl">{item[0]}</h2><p className="mt-4 text-[var(--muted)]">{item[1]}</p></div>)}</div></section><section className="container py-24"><p className="eyebrow">Netzwerk & Verein</p><h2 className="h2 mt-5 max-w-3xl">Netzwerkmitgliedschaft und Vereinsmitgliedschaft sind nicht dasselbe.</h2><p className="mt-7 max-w-2xl text-lg leading-relaxed">Mitglieder des Netzwerks müssen nicht zwingend Mitglieder im Verein sein. Wer sich zusätzlich langfristig für die Ziele engagieren möchte, kann den Verein beitragsfrei unterstützen.</p></section></>;
}
